export interface GpData {
    CCSDS_OMM_VERS: string;
    COMMENT: string;
    CREATION_DATE: string;
    ORIGINATOR: string;
    OBJECT_NAME: string;
    OBJECT_ID: string;
    CENTER_NAME: string;
    REF_FRAME: string;
    TIME_SYSTEM: string;
    MEAN_ELEMENT_THEORY: string;
    EPOCH: string;
    MEAN_MOTION: number;
    ECCENTRICITY: number;
    INCLINATION: number;
    RA_OF_ASC_NODE: number;
    ARG_OF_PERICENTER: number;
    MEAN_ANOMALY: number;
    EPHEMERIS_TYPE: number;
    CLASSIFICATION_TYPE: string;
    NORAD_CAT_ID: number;
    ELEMENT_SET_NO: number;
    REV_AT_EPOCH: number;
    BSTAR: number;
    MEAN_MOTION_DOT: number;
    MEAN_MOTION_DDOT: number;
    SEMIMAJOR_AXIS: number;
    PERIOD: number;
    APOAPSIS: number;
    PERIAPSIS: number;
    OBJECT_TYPE: string;
    RCS_SIZE: string;
    COUNTRY_CODE: string;
    LAUNCH_DATE: string;
    SITE: string;
    DECAY_DATE: string;
    FILE: number;
    GP_ID: number;
    TLE_LINE0: string;
    TLE_LINE1: string;
    TLE_LINE2: string;
}

export interface TLEData {
    TLE_LINE0: string;
    TLE_LINE1: string;
    TLE_LINE2: string;
}

export const CountryCode = {
    ABS: "ABS Global Ltd",
    ALG: "ALGERIA",
    ALL: "ALL",
    AB: "ARAB SATELLITE COMMUNICATIONS ORGANIZATION",
    ARGN: "ARGENTINA",
    AC: "ASIASAT CORP",
    AUS: "AUSTRALIA",
    ASRA: "AUSTRIA",
    AZER: "AZERBAIJAN",
    BHR: "Bahrain",
    BELA: "BELARUS",
    BEL: "BELGIUM",
    BOL: "BOLIVIA",
    BWA: "Botswana",
    BRAZ: "BRAZIL",
    CA: "CANADA",
    CHLE: "CHILE",
    COL: "COLOMBIA",
    CIS: "COMMONWEALTH OF INDEPENDENT STATES",
    PRI: "Commonwealth of Puerto Rico",
    HRV: "Croatia",
    CZE: "Czechia",
    CZCH: "CZECHOSLOVAKIA",
    LKA: "DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA",
    DEN: "DENMARK",
    DJI: "Djibouti",
    ECU: "ECUADOR",
    EGYP: "EGYPT",
    EST: "ESTONIA",
    EUME: "EUROPEAN ORGANIZATION FOR THE EXPLOITATION OF METEOROLOGICAL SATELLITES",
    ESA: "EUROPEAN SPACE AGENCY",
    ESRO: "EUROPEAN SPACE RESEARCH ORGANIZATION",
    EUTELSAT: "EUROPEAN TELECOMMUNICATIONS SATELLITE ORGANIZATION",
    NPL: "FEDERAL DEMOCRATIC REPUBLIC OF NEPAL",
    FIN: "FINLAND",
    FR: "FRANCE",
    FGER: "FRANCE/GERMANY",
    FRIT: "FRANCE/ITALY",
    GER: "GERMANY",
    GLOB: "GLOBALSTAR",
    GREC: "GREECE",
    JOR: "HASHEMITE KINGDOM OF JORDAN",
    HUN: "HUNGARY",
    IND: "INDIA",
    INDO: "INDONESIA",
    INMARSAT: "INTERNATIONAL MARITIME SATELLITE ORGANIZATION",
    ISS: "INTERNATIONAL SPACE STATION",
    INTELSAT: "INTERNATIONAL TELECOMMUNICATIONS SATELLITE ORGANIZATION",
    IRAN: "IRAN",
    IRAQ: "IRAQ",
    ISRA: "ISRAEL",
    IT: "ITALY",
    JPN: "JAPAN",
    KAZ: "KAZAKHSTAN",
    KWT: "Kuwait",
    LAOS: "LAOS",
    LTU: "LITHUANIA",
    LUXE: "LUXEMBOURG",
    MALA: "MALAYSIA",
    MUS: "Mauritius",
    MEX: "MEXICO",
    MDA: "Moldova, Republic of",
    MCO: "Monaco",
    MNG: "MONGOLIA",
    MA: "MOROCCO",
    NETH: "NETHERLANDS",
    NICO: "NEW ICO",
    NZ: "NEW ZEALAND",
    NIG: "NIGERIA",
    NATO: "NORTH ATLANTIC TREATY ORGANIZATION",
    NKOR: "NORTH KOREA",
    NOR: "NORWAY",
    O3B: "O3B NETWORKS",
    GLOBALSTAR: "ORBITAL TELECOMMUNICATIONS SATELLITE",
    PAKI: "PAKISTAN",
    BGD: "PEOPLES REPUBLIC OF BANGLADESH",
    PRC: "PEOPLES REPUBLIC OF CHINA",
    CHBZ: "PEOPLES REPUBLIC OF CHINA/BRAZIL",
    PER: "PERU",
    POL: "POLAND",
    POR: "PORTUGAL",
    RASC: "REGIONAL AFRICAN SATELLITE COMMUNICATIONS ORG",
    AGO: "REPUBLIC OF ANGOLA",
    BGR: "REPUBLIC OF BULGARIA",
    CRI: "REPUBLIC OF COSTA RICA",
    GHA: "REPUBLIC OF GHANA",
    KEN: "REPUBLIC OF KENYA",
    PRY: "REPUBLIC OF PARAGUAY",
    RP: "REPUBLIC OF PHILIPPINES",
    RWA: "REPUBLIC OF RWANDA",
    SVN: "REPUBLIC OF SLOVENIA",
    SDN: "REPUBLIC OF SUDAN",
    MMR: "REPUBLIC OF THE UNION OF MYNAMAR",
    TUN: "REPUBLIC OF TUNISIA",
    ROM: "ROMANIA",
    SAUD: "SAUDI ARABIA",
    SEAL: "SEA LAUNCH DEMO",
    SING: "SINGAPORE",
    STCT: "SINGAPORE/TAIWAN",
    SVK: "Slovakia",
    SES: "SOCIÉTÉ EUROPÉENNE DES SATELLITES",
    SAFR: "SOUTH AFRICA",
    SKOR: "SOUTH KOREA",
    SPN: "SPAIN",
    QAT: "STATE OF QATAR",
    SWED: "SWEDEN",
    SWTZ: "SWITZERLAND",
    TWN: "TAIWAN",
    THAI: "THAILAND",
    TBD: "TO BE DETERMINED/UNKNOWN",
    TURK: "TURKEY",
    TMMC: "TURKMENISTAN/MONACO",
    UGA: "Uganda",
    UKR: "UKRAINE",
    UAE: "UNITED ARAB EMIRATES",
    UK: "UNITED KINGDOM",
    US: "UNITED STATES OF AMERICA",
    USBZ: "UNITED STATES/BRAZIL",
    URY: "URUGUAY",
    VENZ: "VENEZUELA",
    VTNM: "VIETNAM",
    ZWE: "Zimbabwe",
} as const;

export type CountryCode = keyof typeof CountryCode;